shotwell: libchamplain with gobject-introspection enabled is required
error: Package `champlain-gtk-0.12' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `champlain-0.12' not found in specified Vala API directories or GObject-Introspection GIR directories